(ns hello-ring.core
  (:use ring.util.response))

(defn server-information [request]
  (str "ip-address: " (:remote-addr request)))

;My Handler
(defn what-is-my-ip [request]
  (-> (response (server-information request))))

;Middleware -> adds a "Content-Type" header to every response generated by the handler
(defn wrap-content-type [handler content-type]
  (fn [request]
    (let [response (handler request)]
      (assoc-in response [:headers "Content-Type"] content-type))))

(def app
  (-> what-is-my-ip
      (wrap-content-type "text/plain")))
